/* DATA EXPLORATION */
SELECT 
    *
FROM
    my_table;
    
-- Explore All Objects in the Database
SELECT 
    *
FROM
    information_schema.tables;
    
-- Explore All Columns in the Database
SELECT 
    *
FROM
    information_schema.columns;
    
/* DIMENSION EXPLORATION */
-- Explore All Countries our customers come from ?
SELECT DISTINCT
    country
FROM
    my_table_2; 
   
   -- Explore All the Categories "The major Divisions"
SELECT DISTINCT
    category,
    subcategory,
    product_name
FROM
    my_table;

/* DATE EXPLORATION */
-- Find the date of the first and last order
-- How many years of sales are available
-- How many months of sales are available
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    TIMESTAMPDIFF(YEAR,
	MIN(order_date),
	MAX(order_date)) AS order_range_years,
	TIMESTAMPDIFF(MONTH,
	MIN(order_date),
	MAX(order_date)) AS order_range_months
FROM
    my_table_3
WHERE
    order_date != ''; 

-- Find the youngest and the oldest customer
SELECT 
    MIN(birthdate) AS oldest_birthdate,
    TIMESTAMPDIFF(YEAR,
        MIN(birthdate),
        NOW()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    TIMESTAMPDIFF(YEAR,
        MAX(birthdate),
        CURDATE()) AS youngest_age
FROM
    my_table_2
WHERE
    birthdate IS NOT NULL
        AND birthdate != '';

/*  MEASURES EXPLORATION  */
-- Find the Total Sales
SELECT 
    SUM(sales_amount) AS TotalSales
FROM
    my_table_3;
-- find how many items are sold
SELECT 
    SUM(quantity) AS TotalQuantity
FROM
    my_table_3;
-- Find the average selling price
SELECT 
    AVG(price) AS avg_price
FROM
    my_table_3;
-- Find the total number of orders
SELECT 
    COUNT(order_number) AS TotalOrders
FROM
    my_table_3;
-- Find the total number of products 
SELECT 
    COUNT(DISTINCT product_name) AS TotalProducts
FROM
    my_table;
-- Find the total number of customers
SELECT 
    COUNT(customer_key) AS total_customers
FROM
    my_table_2;
-- Find the total number of customers that has placed an order 
SELECT 
    COUNT(customer_key) AS total_customers
FROM
    my_table_3;
-- Generate a report that shows all key metrics of the business 
SELECT 
    'Total Sales' AS Measure_name,
    SUM(sales_amount) AS Measure_value
FROM
    my_table_3 
UNION ALL SELECT 
    'Total Quantity', SUM(quantity)
FROM
    my_table_3 
UNION ALL SELECT 
    'Average Price', ROUND(AVG(price), 0)
FROM
    my_table_3 
UNION ALL SELECT 
    'Total Nr.of Orders', COUNT(DISTINCT order_number)
FROM
    my_table_3 
UNION ALL SELECT 
    'Total Nr.of Products', COUNT(DISTINCT product_name)
FROM
    my_table 
UNION ALL SELECT 
    'Total Nr.of Customers', COUNT(customer_key)
FROM
    my_table_2; -- customers 
    
/*  MAGNITUDE ANALYSIS  
[MEASURE] BY [DIMENSION]*/
-- Find total customers by countries
SELECT 
    country, COUNT(customer_key) AS Total_Customers
FROM
    my_table_2
GROUP BY country
ORDER BY Total_Customers DESC;

-- Find total customers by gender
SELECT 
    gender, COUNT(customer_key) AS Total_Customers
FROM
    my_table_2
GROUP BY gender;

-- Find total products by category
SELECT 
    category, COUNT(product_key) AS Total_Products
FROM
    my_table
GROUP BY category;

-- What is the average costs in each category ?
SELECT 
    category, ROUND(AVG(cost), 0) AS avg_cost
FROM
    my_table
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category ?
SELECT 
    m.category, SUM(mmm.sales_amount) AS Total_revenue
FROM
    my_table m
        LEFT JOIN
    my_table_3 mmm ON m.product_key = mmm.product_key
GROUP BY category
ORDER BY Total_revenue DESC;

-- Find total revenue is generated by each customer ?
SELECT 
    mm.customer_key,
    mm.first_name,
    mm.last_name,
    SUM(mmm.sales_amount) AS Total_revenue
FROM
    my_table_2 mm
        LEFT JOIN
    my_table_3 mmm ON mm.customer_key = mmm.customer_key
GROUP BY mm.customer_key , mm.first_name , mm.last_name
ORDER BY Total_revenue DESC;

-- What is the distribution (Total Quantity) of sold items across countries ?
SELECT 
    country, SUM(mmm.quantity) AS Total_Quantity
FROM
    my_table_2 mm
        LEFT JOIN
    my_table_3 mmm ON mm.customer_key = mmm.customer_key
GROUP BY country
ORDER BY Total_Quantity DESC;


/* Ranking Analysis - Order the values of dimensions by measure 
RANK [DIMENSION] BY [MEASURE] */
-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE ?
SELECT 
    m.product_name, SUM(mmm.sales_amount) AS highest_revenue
FROM
    my_table m
        LEFT JOIN
    my_table_3 mmm ON m.product_key = mmm.product_key
GROUP BY m.product_name
ORDER BY highest_revenue DESC
LIMIT 5;

-- WHAT ARE THE 5 WORST PERFORMING PRODUCTS IN TERMS OF SALES ?
/* DATA EXPLORATION */
SELECT 
    *
FROM
    my_table;
    
-- Explore All Objects in the Database
SELECT 
    *
FROM
    information_schema.tables;
    
-- Explore All Columns in the Database
SELECT 
    *
FROM
    information_schema.columns;
    
/* DIMENSION EXPLORATION */
-- Explore All Countries our customers come from ?
SELECT DISTINCT
    country
FROM
    my_table_2; 
   
   -- Explore All the Categories "The major Divisions"
SELECT DISTINCT
    category,
    subcategory,
    product_name
FROM
    my_table;

/* DATE EXPLORATION */
-- Find the date of the first and last order
-- How many years of sales are available
-- How many months of sales are available
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    TIMESTAMPDIFF(YEAR,
	MIN(order_date),
	MAX(order_date)) AS order_range_years,
	TIMESTAMPDIFF(MONTH,
	MIN(order_date),
	MAX(order_date)) AS order_range_months
FROM
    my_table_3
WHERE
    order_date != ''; 

-- Find the youngest and the oldest customer
SELECT 
    MIN(birthdate) AS oldest_birthdate,
    TIMESTAMPDIFF(YEAR,
        MIN(birthdate),
        NOW()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    TIMESTAMPDIFF(YEAR,
        MAX(birthdate),
        CURDATE()) AS youngest_age
FROM
    my_table_2
WHERE
    birthdate IS NOT NULL
        AND birthdate != '';

/*  MEASURES EXPLORATION  */
-- Find the Total Sales
SELECT 
    SUM(sales_amount) AS TotalSales
FROM
    my_table_3;
-- find how many items are sold
SELECT 
    SUM(quantity) AS TotalQuantity
FROM
    my_table_3;
-- Find the average selling price
SELECT 
    AVG(price) AS avg_price
FROM
    my_table_3;
-- Find the total number of orders
SELECT 
    COUNT(order_number) AS TotalOrders
FROM
    my_table_3;
-- Find the total number of products 
SELECT 
    COUNT(DISTINCT product_name) AS TotalProducts
FROM
    my_table;
-- Find the total number of customers
SELECT 
    COUNT(customer_key) AS total_customers
FROM
    my_table_2;
-- Find the total number of customers that has placed an order 
SELECT 
    COUNT(customer_key) AS total_customers
FROM
    my_table_3;
-- Generate a report that shows all key metrics of the business 
SELECT 
    'Total Sales' AS Measure_name,
    SUM(sales_amount) AS Measure_value
FROM
    my_table_3 
UNION ALL SELECT 
    'Total Quantity', SUM(quantity)
FROM
    my_table_3 
UNION ALL SELECT 
    'Average Price', ROUND(AVG(price), 0)
FROM
    my_table_3 
UNION ALL SELECT 
    'Total Nr.of Orders', COUNT(DISTINCT order_number)
FROM
    my_table_3 
UNION ALL SELECT 
    'Total Nr.of Products', COUNT(DISTINCT product_name)
FROM
    my_table 
UNION ALL SELECT 
    'Total Nr.of Customers', COUNT(customer_key)
FROM
    my_table_2; -- customers 
    
/*  MAGNITUDE ANALYSIS  
[MEASURE] BY [DIMENSION]*/
-- Find total customers by countries
SELECT 
    country, COUNT(customer_key) AS Total_Customers
FROM
    my_table_2
GROUP BY country
ORDER BY Total_Customers DESC;

-- Find total customers by gender
SELECT 
    gender, COUNT(customer_key) AS Total_Customers
FROM
    my_table_2
GROUP BY gender;

-- Find total products by category
SELECT 
    category, COUNT(product_key) AS Total_Products
FROM
    my_table
GROUP BY category;

-- What is the average costs in each category ?
SELECT 
    category, ROUND(AVG(cost), 0) AS avg_cost
FROM
    my_table
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category ?
SELECT 
    m.category, SUM(mmm.sales_amount) AS Total_revenue
FROM
    my_table m
        LEFT JOIN
    my_table_3 mmm ON m.product_key = mmm.product_key
GROUP BY category
ORDER BY Total_revenue DESC;

-- Find total revenue is generated by each customer ?
SELECT 
    mm.customer_key,
    mm.first_name,
    mm.last_name,
    SUM(mmm.sales_amount) AS Total_revenue
FROM
    my_table_2 mm
        LEFT JOIN
    my_table_3 mmm ON mm.customer_key = mmm.customer_key
GROUP BY mm.customer_key , mm.first_name , mm.last_name
ORDER BY Total_revenue DESC;

-- What is the distribution (Total Quantity) of sold items across countries ?
SELECT 
    country, SUM(mmm.quantity) AS Total_Quantity
FROM
    my_table_2 mm
        LEFT JOIN
    my_table_3 mmm ON mm.customer_key = mmm.customer_key
GROUP BY country
ORDER BY Total_Quantity DESC;


/* Ranking Analysis - Order the values of dimensions by measure 
RANK [DIMENSION] BY [MEASURE] */
-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE ?
SELECT 
    m.product_name, SUM(mmm.sales_amount) AS highest_revenue
FROM
    my_table m
        LEFT JOIN
    my_table_3 mmm ON m.product_key = mmm.product_key
GROUP BY m.product_name
ORDER BY highest_revenue DESC
LIMIT 5;

-- WHAT ARE THE 5 WORST PERFORMING PRODUCTS IN TERMS OF SALES ?
SELECT 
    m.product_name, SUM(mmm.sales_amount) least_sales
FROM
    my_table m
        INNER JOIN
    my_table_3 mmm ON m.product_key = mmm.product_key
GROUP BY product_name
ORDER BY least_sales
LIMIT 5;

-- WHICH ARE THE TOP YEARS GENERATED HUGE REVENUE
SELECT 
    YEAR(order_date) AS 'o', SUM(sales_amount) AS total_sales
FROM
    my_table_3
WHERE
    YEAR(order_date) IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY total_sales DESC;

